os:
  - osx
language: cpp
compiler:
  - gcc
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq libboost-all-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install maven; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install cpp-coveralls wheel; fi
  
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install caskroom/cask/brew-cask; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install virtualbox; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install docker; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install docker-machine; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make python; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mvn test -f java/pom.xml; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make test; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make test_gcov --always-make; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python setup.py sdist; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python setup.py bdist_wheel; fi
  
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then java/src/main/bin/build.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mvn clean deploy -f java/pom.xml --settings java/settings.xml; fi
  
after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then coveralls --exclude lib --exclude tests --gcov-options '\-lp'; fi
